"use client";

import { useActionState, useState } from "react";
import { showDetailedLearningLogs } from "@/ai/flows/show-detailed-learning-logs";
import { useContent } from "@/context/content-context";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Loader2, FileClock } from "lucide-react";

type State = {
  logs: string | null;
  error: string | null;
};

export default function LogsPage() {
  const { content: availableContent } = useContent();
  const [contentId, setContentId] = useState<string | null>(null);

  const [state, formAction, isPending] = useActionState(
    async (prevState: State, formData: FormData): Promise<State> => {
      const id = formData.get("contentId") as string;
      if (!id) {
        return { logs: null, error: "Please select a content to view logs." };
      }
      try {
        const result = await showDetailedLearningLogs({ contentId: id });
        return { logs: result.logs, error: null };
      } catch (error) {
        console.error(error);
        return { logs: null, error: "Failed to fetch learning logs." };
      }
    },
    { logs: null, error: null }
  );

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Learning Logs</h1>
        <p className="text-muted-foreground">
          Review what your AI tutor has learned from your study materials.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Generate Logs</CardTitle>
          <CardDescription>
            Select a piece of content to see the detailed learning logs
            generated by the AI.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form action={formAction} className="space-y-4">
            <Select
              name="contentId"
              onValueChange={setContentId}
              disabled={isPending || availableContent.length === 0}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select content..." />
              </SelectTrigger>
              <SelectContent>
                {availableContent.map((content) => (
                  <SelectItem key={content.id} value={content.id}>
                    {content.title}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button type="submit" disabled={isPending || !contentId}>
              {isPending ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <FileClock className="mr-2 h-4 w-4" />
              )}
              Show Logs
            </Button>
          </form>
        </CardContent>
      </Card>

      {isPending && (
        <Card>
          <CardContent className="p-6 flex items-center justify-center h-64">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
          </CardContent>
        </Card>
      )}

      {state.error && !isPending && (
        <Card className="border-destructive">
          <CardHeader>
            <CardTitle className="text-destructive">Error</CardTitle>
          </CardHeader>
          <CardContent>
            <p>{state.error}</p>
          </CardContent>
        </Card>
      )}

      {state.logs && !isPending && (
        <Card>
          <CardHeader>
            <CardTitle>Detailed Logs</CardTitle>
            <CardDescription>
              Showing logs for:{" "}
              {availableContent.find((c) => c.id === contentId)?.title}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-96 w-full rounded-md border p-4 bg-muted/50">
              <pre className="text-sm whitespace-pre-wrap font-mono">
                {state.logs}
              </pre>
            </ScrollArea>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
